### PR TITLE
Now sends custom JSON message.

### LINKED ISSUE #22: Turn off production error stack traces
https://documentation.bloomreach.com/14/library/concepts/error-pages-and-error-handling/1.-handling-error-codes-and-exceptions-by-the-web.xml.html

### PR DESCRIPTION
**Pull request by Michael-Kochis**
Phillip, 

Please evaluate my basic code.
More work to do, but we can use this as a template.

### CODE REVIEW

File: src/main/java/com/revature/g2g/aspects/ControllerExceptionAspect.java [hunk 1]
```diff
@@ -1,44 +1,57 @@
...
+	 * @Around("within(com.revature.g2g.api.controllers.*)") public ResponseEntity
+	 * logControllers(ProceedingJoinPoint jp) { ResponseEntity result = null;
+	 * 
+	 * try { result = (ResponseEntity) jp.proceed(); return result; } catch
+	 * (Throwable e) { System.out.println("Punch line two"); String controlLog =
+	 * jp.getTarget() + " invoked " + jp.getSignature() + " throwing: " + e;
+	 * loggerSingleton.getExceptionLogger().warn(controlLog, e); MessageTemplate
+	 * errorMessage = new MessageTemplate("Custom Internal Server Error"); return
+	 * ResponseEntity.status(HttpStatus.ACCEPTED).body(errorMessage); } }
+	 */
```
Comment (pjlawrence) [inline src/main/java/com/revature/g2g/aspects/ControllerExceptionAspect.java]: Please remove commented code

**Review by IncarnateGaming — CHANGES_REQUESTED** [review]
Please remove the stack trace file

File: src/main/java/com/revature/g2g/aspects/ControllerExceptionAspect.java (hunk 1 above)
Comment (Michael-Kochis) [reply src/main/java/com/revature/g2g/aspects/ControllerExceptionAspect.java]: Code is now removed.
